export const Employelist = [
  {name:"Rubul tanti",
    id: "1",
    email: "alice.johnson@example.com",
    password: "id123",
    tasks: [
      {
        title: "Complete frontend module",
        description: "Finalize the remaining sections in the frontend development module.",
        date: "2024-11-15",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Update documentation",
        description: "Revise and update the project documentation with recent changes.",
        date: "2024-11-10",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Fix CSS bugs",
        description: "Identify and resolve styling issues in the app's CSS.",
        date: "2024-11-12",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Design new UI components",
        description: "Create design mockups for the new UI components.",
        date: "2024-11-18",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
  },
  {name:"Nitu tanti",
    id: "2",
    email: "1",
    password: "1",
    tasks: [
      {
        title: "Optimize page load speed",
        description: "Improve website performance by reducing load time.",
        date: "2024-11-13",
        active: true,
        newTask:false,
        completed: false,
        failed: false,
      },
      {
        title: "Revise codebase",
        description: "Review and refactor outdated sections of the codebase.",
        date: "2024-11-11",
        active: false,
        newTask: true,
        completed:false,
        failed: false,
      },
      {
        title: "Fix JavaScript errors",
        description: "Debug and resolve any JavaScript errors found in the console.",
        date: "2024-11-14",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Implement login feature",
        description: "Add user login functionality with form validation.",
        date: "2024-11-12",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },
  { name:"rahul",
    id: "4",
    email: "diana.prince@example.com",
    password: "id123",
    tasks:[
      {
        title: "Test cross-browser compatibility",
        description: "Verify the app functions correctly across various browsers.",
        date: "2024-11-15",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Update landing page design",
        description: "Redesign the landing page for a modern look and feel.",
        date: "2024-11-09",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Improve accessibility",
        description: "Make adjustments to improve web accessibility standards.",
        date: "2024-11-13",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Enhance mobile layout",
        description: "Optimize the layout for better mobile device performance.",
        date: "2024-11-12",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
  },
  { name:"krishna ",
    id: "5",
    email: "edward.elric@example.com",
    password: "id123",
    tasks: [
      {
        title: "Implement SEO features",
        description: "Enhance SEO by adding meta tags and improving keywords.",
        date: "2024-11-14",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Redesign footer",
        description: "Revamp the footer with new links and contact information.",
        date: "2024-11-10",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Debug server errors",
        description: "Investigate and fix any server-side errors.",
        date: "2024-11-15",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Conduct code review",
        description: "Review team code submissions for quality and consistency.",
        date: "2024-11-11",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
  },
];
export const Adminlist=[
  { name:"Rubul tanti",
    id: "1",
    email: "admin1@example.com",
    password: "Admin123",
    asignTasks:[ {
      title: "Implement login feature",
      description: "Add user login functionality with form validation.",
      date: "2024-11-12",
      status:"newTask",
      asignTo:'Nitu tanti'
    },{
      title: "Fix JavaScript errors",
      description: "Debug and resolve any JavaScript errors found in the console.",
      date: "2024-11-14",
     status:'newTask',
     asignTo:"Nitu tanti"
    }]
  },
];



console.log("a")

 